services:
  circle-detection:
    build: .
    container_name: circle-detection
    volumes:
      - ./app:/app
      - ./requirements:/requirements
    command: /bin/bash
    stdin_open: true
    tty: true